"""gsagas

Revision ID: 67c3e3746dd1
Revises: 1501d30299ac
Create Date: 2022-02-14 11:15:37.533576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c3e3746dd1'
down_revision = '1501d30299ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(length=50000), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsletterInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateSent', sa.DateTime(), nullable=False),
    sa.Column('letterId', sa.Integer(), nullable=False),
    sa.Column('receiverId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['letterId'], ['Newsletter.id'], ),
    sa.ForeignKeyConstraint(['receiverId'], ['SignupsNewsletter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsletterInfo')
    op.drop_table('Newsletter')
    # ### end Alembic commands ###
